### ISSUE TITLE
The separate VM rule should is a `SHOULD` vs `MUST` DRS rule needs to change

### ISSUE THREAD

**Issue by akamitmishra** [cloudfoundry/bosh-vsphere-cpi-release#223] opened 2019-07-01 18:25 UTC
**Describe the bug**
We are using Bosh to deploy 6 VMs into a cluster with 5 hosts. Bosh has been configured to create these 6 VMs with ‘Separate Virtual Machines’ anti-affinity.
when looking at the VCenter GUI, I see that all 6 VMs are powered on, and 2 VMs are running on the same host.

**To Reproduce**
1.We are using Bosh to deploy 6 VMs into a cluster with 5 hosts. Bosh has been configured to create these 6 VMs with ‘Separate Virtual Machines’ anti-affinity.
when looking at the VCenter GUI, I see that all 6 VMs are powered on, and 2 VMs are running on the same host.

**CPI Error Log**
[13067 85312 :001676: ftc 06/06/2019 13:58:51 -0600 INFO ] STDOUT - Task 10 | 19:45:28 | Creating missing vms: apply-addons/82e2cbfb-d28c-4903-9865-a086609d075b (0) (00:00:46)
[13067 85312 :001677: ftc 06/06/2019 13:58:51 -0600 INFO ] STDOUT - L Error: Unknown CPI error 'Unknown' with message 'Could not power on VM '<[Vim.VirtualMachine] vm-30420>': DRS cannot find a host to power on or migrate the virtual machine.' in 'create_vm' CPI method (CPI request ID: 'cpi-405264')

Even after the error VMs get created. 

**Expected behavior**
We expect that there should be just 5 VMs created on 5 hosts in this situation.

**Screenshots**

**Release Version & Related Info (please complete the following information):**
 - CPI Version 
 - BOSH Director Version
 - Stemcell Name & Version
 - vCenter Version 
6.5
 - NSX(T/V) Version (If using)

**Additional context**
Discussed this on # bosh-cpi-dev slack channel and @EleanorRigby believes that this is a bug

```Amit Mishra [Jun 29th at 10:00 AM]
Hello - We are using Bosh to deploy 6 VMs into a cluster with 5 hosts. Bosh has been configured to create these 6 VMs with ‘Separate Virtual Machines’ anti-affinity. I believe Bosh uses vCO to interact with VCenter. Unfortunately I do not have the commands sent by Bosh. Is there a way to collect these from VCenter?

Bosh reports the following error when attempting to start the 6th VM:

[13067 85312 :001676: ftc 06/06/2019 13:58:51 -0600 INFO ] STDOUT - Task 10 | 19:45:28 | Creating missing vms: apply-addons/82e2cbfb-d28c-4903-9865-a086609d075b (0) (00:00:46)
[13067 85312 :001677: ftc 06/06/2019 13:58:51 -0600 INFO ] STDOUT - L Error: Unknown CPI error 'Unknown' with message 'Could not power on VM '<[Vim.VirtualMachine] vm-30420>': DRS cannot find a host to power on or migrate the virtual machine.' in 'create_vm' CPI method (CPI request ID: 'cpi-405264')

This is expected, since there are not enough hosts (5) to run the 6th VM. I do not see any further output from Bosh after the above failure.

However, when looking at the VCenter GUI, I see that all 6 VMs are powered on, and 2 VMs are running on the same host.

Bosh created a VM/Host Rule named ‘separate-vms-rule’ which has 6 VMs in it. The VM/Host Rule Details state “The listed 6 Virtual Machines must run on different hosts.”, but that isn’t the case since 2 VMs run on the same host.

Is this expected? or is there a way to change the behavior?

5 replies

Amit Mishra  [2 hours ago]
Any help here would be really appreciated? (edited)

Tushar  [2 hours ago]
Hi Amit

Tushar  [2 hours ago]
The separate VM rule should is a `SHOULD` vs `MUST` DRS rule and therefore should allow 2 VMs tower on the same host if no. of VMs is greater than no. of hosts.

Tushar  [2 hours ago]
CPI-team will accept it as a bug request here: https://github.com/cloudfoundry/bosh-vsphere-cpi-release/issues

The bug template will guide you in filling all required info to fix it.

Amit Mishra  [1 hour ago]
Thanks Tushar!```

**Comment by EleanorRigby** [comment] 2019-07-01 18:30
Please attach complete CPI logs and various product versions that you are using.

**Comment by EleanorRigby** [comment] 2019-07-01 18:32
```
Expected behavior
We expect that there should be just 5 VMs created on 5 hosts in this situation.
```
This cannot happen as the DRS rule is prescriptive and not binding. 

Looks like : *Feature Change to make DRS rule mandatory*

**Comment by EleanorRigby** [comment] 2019-07-01 18:35
The error and description are confusing. The description says that 6 VMs were created. While the error says "Not able to Power On VM for lack of hosts". Can you explain the scenario a bit more?

**Comment by amishra1982** [comment] 2019-07-01 20:38
bosh release 270.1.1
vsphere-cpi 52
and we are not using opsman

The error says that "Not able to Power On VM for lack of hosts" but the VMs still get created. Yep - same issue that @thorsten-avaya  was seeing

[cc.txt](https://github.com/cloudfoundry/bosh-vsphere-cpi-release/files/3347247/cc.txt)
[tasks.txt](https://github.com/cloudfoundry/bosh-vsphere-cpi-release/files/3347248/tasks.txt)

**Comment by svrc-pivotal** [comment] 2020-01-16 16:16
What’s interesting in this to me is the VM/VM Anti-affinity rule is supposed to by soft - there is no way to make it mandatory.    the error from the VIM API might only be a warning.

**Comment by julian-hj** [comment] 2021-07-29 22:33
closing and re-opening to create a tracker story.

**Comment by julian-hj** [comment] 2021-09-10 21:44
After looking at the attached `tasks.txt` it appears to me that there are two different issues here:

1. vSphere didn't catch the anti-affinity rule in time and allowed one extra VM to be created.
2. The errand VM is getting deployed into the same anti-affinity AZ as the other VMs, and failing to power on.

The second issue could be easily addressed by creating a different AZ for the errands, and not setting anti-affinity on it. (Presumably, there isn't any real reason for anti-affinity in this case.)

The first issue, we are no longer able to reproduce, either with integration tests or manually with bosh deployments. Even if we disable canaries and let all the VMs get created simultaneously, vSphere is catching the conflict and refusing to power on the extra VM with the error `'Could not power on VM '<[Vim.VirtualMachine] vm-62>': This operation would violate a virtual machine affinity/anti-affinity rule.'`

So, I am going to close this issue. Please feel free to open it again or post a new issue if you are still able to reproduce the problem.

**Closed by julian-hj** 2021-09-10 21:44 UTC
Labels: feature, unscheduled
