### ISSUE TITLE
Delete VM "A specified parameter is not correct.'' in ''delete_vm'' CPI method

### ISSUE THREAD

**Issue by pivotal-ben-chacko** [cloudfoundry/bosh-vsphere-cpi-release#182] opened 2018-12-17 16:02 UTC
**Describe the bug**
While upgrading healthwatch, BOSH failed to delete a VM. In VMware, the log show an initial message of "Another task is already running" followed by several messages saying that the parameter is incorrect.

**CPI Error Log**
[task-93363-cpi.txt](https://github.com/cloudfoundry/bosh-vsphere-cpi-release/files/2681615/task-93363-cpi.txt)

**Expected behavior**
Apply changes should complete the upgrade with no errors

**Release Version & Related Info (please complete the following information):**
 OpsManager 2.1.18
PAS 2.1.17
Healthwatch 1.3.2
Isolation Segment 2.1.14
Metrics 1.5
 
The CPI and BOSH versions would be whatever comes in 2.1.18.
 
PAS stemcell version is 3541.59. I don’t see a listing for the director stemcell in the Stemcell Library. Not sure how to tell on that one.
 
vCenter is 6.0 but it will take me some more time to find the exact version.
 
We don’t use NSX.

**Comment by EleanorRigby** [comment] 2019-01-16 02:38
looks like the error is coming while detaching persistent disks from the VM. Does this error still persist?

**Comment by pivotal-ben-chacko** [comment] 2019-01-16 15:35
Customer who encountered this issue has not had a chance to run the deployment since, but would like to avoid it happening in the future.

**Comment by EleanorRigby** [comment] 2019-03-05 20:02
Closing because of insufficient evidence/re-runs to verify and reproduce the issue.

Feel free to open this in future.

**Closed by EleanorRigby** 2019-03-05 20:02 UTC
Labels: Bug
