### ISSUE TITLE
cpi deletes ip from NSX LB Pool even if it didn't add it

### ISSUE THREAD

**Issue by xetamus** [cloudfoundry/bosh-vsphere-cpi-release#181] opened 2018-12-12 21:37 UTC
**Describe the bug**
When configuring a bosh director on vSphere with NSX-T, if IPs are manually added to a load balancer pool and then the vm is deleted by the bosh director, the IP for that instance will be removed from the NSX-T Load Balancer Server Pool. The CPI should only remove IPs from Server Pools that are defined via `cloud_properties`.

**To Reproduce**
1. Add IPs of any bosh managed VMs to an NSX-T Load Balancer Server Pool
2. Run a `bosh delete-vm` on the instance whose IP was added the pool

The IP will have been removed from the Server Pool although we never explicitly defined the relationship within bosh.

**Expected behavior**
Because we did not explicitly define the relationship to the Server Pool through bosh, bosh should not delete the IP from the Server Pool.

**Release Version & Related Info (please complete the following information):**
 - CPI Version : 50
 - BOSH Director Version : 267.8
 - Stemcell Name & Version : Xenial 97.28
 - vCenter Version : 6.5.0.13000 Build 8024368
 - NSX(T/V) Version (If using) : NSX-T 2.3.0.0.0.10085361

**Additional context**

The following code block is what's relevant here as per @EleanorRigby :

```
begin
            @nsxt_provider.remove_vm_from_server_pools(vm_ip)
          rescue => e
            logger.info("Failed to remove VM from ServerPool: #{e.message}")
          end
```

**Comment by nehagjain15** [comment] 2018-12-12 23:57
@xetamus When we added the feature for NSX-T Load balancer, CPI started maintaining the lifecycle of ServerPools for VM's created by CPI. I think ServerPools cannot be tagged so there is no way for CPI to find out if the entry for VM's IP was added by BOSH/externally. We will look into if we can use display_name property of PoolMember to differentiate this

**Comment by EleanorRigby** [comment] 2018-12-18 17:55
@xetamus @nehagjain15 : Just to correct above statement , CPI maintains *lifecycle of VM's membership in a Server Pool*.  Server Pool itself is expected to be present and is not cleaned up by CPI.

**Comment by Nilesh7756** [comment] 2018-12-21 09:45
We are facing this same issue on PAS + NSX-T setup, here NSX-T LB Members are getting deleted for NSX-T LB Member pool.

Below are observations on this issue:

We have manually configured NSX-T LB with 3 Static Server Pool Members of  GO-ROUTER IP as a backend server.

**Scenario 1**: When update-resurrection ON
- We are disconnecting Network card from VC for one of GO-ROUTER IP.
- BOSH cloud health check re-delete and re-create new GO-ROUTER VM.
- There CPI  the VM IP from NSX-T LB ServerPool.
```I, [2018-12-21T06:19:36.815858 #11666]  INFO -- [req_id cpi-411425]: Removing vm with ip: '192.168.5.23', port_no:  from ServerPool: a0eb07bd-7086-45a4-8766-9a458142fe78 ```
- It didn't re-add the entry once new VM gets created. 

**Scenario 2**: When update-resurrection OFF
- We are disconnecting Network card from VC for one of GO-ROUTER IP.
- BOSH cloud health check will not re-delete and re-create new GO-ROUTER VM.
- Here Pool Member went in DOWN state
- Once VM gets the network up, it will change is Pool Member state as UP.

The CPI should only remove IPs from Server Pools that are defined via cloud_properties.

**CPI Error Log**
Can be obtained by running `bosh <env params> task <failed-task-id> --cpi`

```
Task 49066

/var/vcap/data/packages/vsphere_cpi/6a846bc126536d490e43d8762cff951456af41ca/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2018-12-21T06:18:58.359659 #11591]  INFO -- [req_id cpi-703464]: Starting info...
D, [2018-12-21T06:18:58.362356 #11591] DEBUG -- [req_id cpi-703464]: Running method 'RetrieveServiceContent'...
D, [2018-12-21T06:18:58.444785 #11591] DEBUG -- [req_id cpi-703464]: Running method 'Login'...
I, [2018-12-21T06:18:58.487379 #11591]  INFO -- [req_id cpi-703464]: Finished info in 0.13 seconds
D, [2018-12-21T06:18:58.488042 #11591] DEBUG -- [req_id cpi-703464]: Running method 'Logout'...
/var/vcap/data/packages/vsphere_cpi/6a846bc126536d490e43d8762cff951456af41ca/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2018-12-21T06:19:06.260522 #11610]  INFO -- [req_id cpi-106898]: Starting has_vm...
D, [2018-12-21T06:19:06.263141 #11610] DEBUG -- [req_id cpi-106898]: Running method 'RetrieveServiceContent'...
D, [2018-12-21T06:19:06.325200 #11610] DEBUG -- [req_id cpi-106898]: Running method 'Login'...
D, [2018-12-21T06:19:06.364810 #11610] DEBUG -- [req_id cpi-106898]: Running method 'FindByInventoryPath'...
D, [2018-12-21T06:19:06.375368 #11610] DEBUG -- [req_id cpi-106898]: Running method 'CreateContainerView'...
D, [2018-12-21T06:19:06.477271 #11610] DEBUG -- [req_id cpi-106898]: Running method 'ContinueRetrievePropertiesEx'...
I, [2018-12-21T06:19:06.532790 #11610]  INFO -- [req_id cpi-106898]: Finished has_vm in 0.27 seconds
D, [2018-12-21T06:19:06.533522 #11610] DEBUG -- [req_id cpi-106898]: Running method 'Logout'...
/var/vcap/data/packages/vsphere_cpi/6a846bc126536d490e43d8762cff951456af41ca/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2018-12-21T06:19:23.974770 #11646]  INFO -- [req_id cpi-733803]: Starting info...
D, [2018-12-21T06:19:23.977772 #11646] DEBUG -- [req_id cpi-733803]: Running method 'RetrieveServiceContent'...
D, [2018-12-21T06:19:24.056713 #11646] DEBUG -- [req_id cpi-733803]: Running method 'Login'...
I, [2018-12-21T06:19:24.095193 #11646]  INFO -- [req_id cpi-733803]: Finished info in 0.12 seconds
D, [2018-12-21T06:19:24.096440 #11646] DEBUG -- [req_id cpi-733803]: Running method 'Logout'...
/var/vcap/data/packages/vsphere_cpi/6a846bc126536d490e43d8762cff951456af41ca/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2018-12-21T06:19:31.558495 #11666]  INFO -- [req_id cpi-411425]: Starting delete_vm...
D, [2018-12-21T06:19:31.562148 #11666] DEBUG -- [req_id cpi-411425]: Running method 'RetrieveServiceContent'...
D, [2018-12-21T06:19:31.639984 #11666] DEBUG -- [req_id cpi-411425]: Running method 'Login'...
I, [2018-12-21T06:19:31.677268 #11666]  INFO -- [req_id cpi-411425]: Deleting vm: vm-a07eb61a-4d1d-4fa4-9eec-29ade81c2225
D, [2018-12-21T06:19:31.677478 #11666] DEBUG -- [req_id cpi-411425]: Running method 'FindByInventoryPath'...
D, [2018-12-21T06:19:31.684246 #11666] DEBUG -- [req_id cpi-411425]: Running method 'CreateContainerView'...
D, [2018-12-21T06:19:31.825468 #11666] DEBUG -- [req_id cpi-411425]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-21T06:19:32.069248 #11666] DEBUG -- [req_id cpi-411425]: Running method 'PowerOffVM_Task'...
D, [2018-12-21T06:19:32.093800 #11666] DEBUG -- [req_id cpi-411425]: Starting task 'VirtualMachine.powerOff'...
D, [2018-12-21T06:19:34.139381 #11666] DEBUG -- [req_id cpi-411425]: Finished task 'VirtualMachine.powerOff' after 2.045347407 seconds
I, [2018-12-21T06:19:34.227536 #11666]  INFO -- [req_id cpi-411425]: Cleaning current agent env from vm 'vm-a07eb61a-4d1d-4fa4-9eec-29ade81c2225'
D, [2018-12-21T06:19:34.317325 #11666] DEBUG -- [req_id cpi-411425]: Running method 'DeleteDatastoreFile_Task'...
D, [2018-12-21T06:19:34.351544 #11666] DEBUG -- [req_id cpi-411425]: Starting task 'FileManager.deleteFile'...
D, [2018-12-21T06:19:35.376496 #11666] DEBUG -- [req_id cpi-411425]: Finished task 'FileManager.deleteFile' after 1.024704459 seconds
D, [2018-12-21T06:19:35.376723 #11666] DEBUG -- [req_id cpi-411425]: Running method 'DeleteDatastoreFile_Task'...
D, [2018-12-21T06:19:35.398120 #11666] DEBUG -- [req_id cpi-411425]: Starting task 'FileManager.deleteFile'...
D, [2018-12-21T06:19:36.423781 #11666] DEBUG -- [req_id cpi-411425]: Finished task 'FileManager.deleteFile' after 1.025310779 seconds
I, [2018-12-21T06:19:36.424115 #11666]  INFO -- [req_id cpi-411425]: NSX-T networks found for vm 'vm-a07eb61a-4d1d-4fa4-9eec-29ade81c2225': ["nsx.LogicalSwitch: f67c1a71-7c7c-4a08-85f9-1ce400e71edb"]
I, [2018-12-21T06:19:36.424339 #11666]  INFO -- [req_id cpi-411425]: Searching for LogicalPorts for vm 'vm-a07eb61a-4d1d-4fa4-9eec-29ade81c2225'
I, [2018-12-21T06:19:36.470948 #11666]  INFO -- [req_id cpi-411425]: Searching VIFs with 'owner_vm_id: 500d3c93-f2ba-e131-f572-bc946b1e93e9'
I, [2018-12-21T06:19:36.492548 #11666]  INFO -- [req_id cpi-411425]: Searching LogicalPorts with 'attachment_id: 273cd177-a298-4836-af12-d07f9e6625c8'
I, [2018-12-21T06:19:36.516316 #11666]  INFO -- [req_id cpi-411425]: LogicalPorts found for vm 'vm-a07eb61a-4d1d-4fa4-9eec-29ade81c2225': ["c1d7be4a-a455-4d46-b494-9b98d17cfb94"]'
I, [2018-12-21T06:19:36.815858 #11666]  INFO -- [req_id cpi-411425]: Removing vm with ip: '192.168.5.23', port_no:  from ServerPool: a0eb07bd-7086-45a4-8766-9a458142fe78 
D, [2018-12-21T06:19:36.857572 #11666] DEBUG -- [req_id cpi-411425]: Running method 'Destroy_Task'...
D, [2018-12-21T06:19:36.886849 #11666] DEBUG -- [req_id cpi-411425]: Starting task 'VirtualMachine.destroy'...
D, [2018-12-21T06:19:39.962691 #11666] DEBUG -- [req_id cpi-411425]: Finished task 'VirtualMachine.destroy' after 3.075544382 seconds
I, [2018-12-21T06:19:39.962837 #11666]  INFO -- [req_id cpi-411425]: Deleted vm: vm-a07eb61a-4d1d-4fa4-9eec-29ade81c2225
I, [2018-12-21T06:19:39.963000 #11666]  INFO -- [req_id cpi-411425]: Finished delete_vm in 8.4 seconds
D, [2018-12-21T06:19:39.963656 #11666] DEBUG -- [req_id cpi-411425]: Running method 'Logout'...
/var/vcap/data/packages/vsphere_cpi/6a846bc126536d490e43d8762cff951456af41ca/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2018-12-21T06:19:50.754471 #11833]  INFO -- [req_id cpi-431115]: Starting info...
D, [2018-12-21T06:19:50.757663 #11833] DEBUG -- [req_id cpi-431115]: Running method 'RetrieveServiceContent'...
D, [2018-12-21T06:19:50.822319 #11833] DEBUG -- [req_id cpi-431115]: Running method 'Login'...
I, [2018-12-21T06:19:50.861240 #11833]  INFO -- [req_id cpi-431115]: Finished info in 0.11 seconds
D, [2018-12-21T06:19:50.862003 #11833] DEBUG -- [req_id cpi-431115]: Running method 'Logout'...
/var/vcap/data/packages/vsphere_cpi/6a846bc126536d490e43d8762cff951456af41ca/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2018-12-21T06:19:57.965274 #11853]  INFO -- [req_id cpi-958342]: Starting create_vm...
D, [2018-12-21T06:19:57.968542 #11853] DEBUG -- [req_id cpi-958342]: Running method 'RetrieveServiceContent'...
D, [2018-12-21T06:19:58.041025 #11853] DEBUG -- [req_id cpi-958342]: Running method 'Login'...
D, [2018-12-21T06:19:58.075804 #11853] DEBUG -- [req_id cpi-958342]: Running method 'FindByInventoryPath'...
D, [2018-12-21T06:19:58.081356 #11853] DEBUG -- [req_id cpi-958342]: Running method 'CreateContainerView'...
D, [2018-12-21T06:19:58.176952 #11853] DEBUG -- [req_id cpi-958342]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-21T06:19:58.245516 #11853] DEBUG -- [req_id cpi-958342]: All clusters provided: {"pas-foundation-cluster-2"=>#<VSphereCloud::ClusterConfig:0x000055d41c80d568 @name="pas-foundation-cluster-2", @config={"resource_pool"=>"PAS2"}>}
D, [2018-12-21T06:19:58.245715 #11853] DEBUG -- [req_id cpi-958342]: Running method 'FindByInventoryPath'...
I, [2018-12-21T06:19:58.306491 #11853]  INFO -- [req_id cpi-958342]: Using global ephemeral disk datastore pattern: ^(PAS2_vsanDatastore)$
D, [2018-12-21T06:19:58.347401 #11853] DEBUG -- [req_id cpi-958342]: Found requested resource pool: <[Vim.ResourcePool] resgroup-1499>
D, [2018-12-21T06:19:58.637882 #11853] DEBUG -- [req_id cpi-958342]: Initial Storage Options for creating ephemeral disk from pattern: ["PAS2_vsanDatastore"]
D, [2018-12-21T06:19:58.638062 #11853] DEBUG -- [req_id cpi-958342]: Storage Options for creating ephemeral disk are: ["PAS2_vsanDatastore"]
I, [2018-12-21T06:19:58.638208 #11853]  INFO -- [req_id cpi-958342]: Checking if ip '192.168.5.23' is in use
D, [2018-12-21T06:19:58.638294 #11853] DEBUG -- [req_id cpi-958342]: Running method 'FindByIp'...
I, [2018-12-21T06:19:58.647836 #11853]  INFO -- [req_id cpi-958342]: No IP conflicts detected
I, [2018-12-21T06:19:58.648111 #11853]  INFO -- [req_id cpi-958342]: Creating vm: vm-0ccac867-38e3-48bb-afc4-f91fe982b1d0 on <[Vim.ClusterComputeResource] domain-c1291> stored in <[Vim.Datastore] datastore-1507>
D, [2018-12-21T06:19:58.648211 #11853] DEBUG -- [req_id cpi-958342]: Running method 'FindByInventoryPath'...
D, [2018-12-21T06:19:58.655354 #11853] DEBUG -- [req_id cpi-958342]: Running method 'CreateContainerView'...
D, [2018-12-21T06:19:58.761393 #11853] DEBUG -- [req_id cpi-958342]: Running method 'ContinueRetrievePropertiesEx'...
I, [2018-12-21T06:19:58.831596 #11853]  INFO -- [req_id cpi-958342]: Searching for stemcell sc-c94935ea-2af4-4416-8947-665d115e7474 on datastore PAS2_vsanDatastore
D, [2018-12-21T06:19:58.831772 #11853] DEBUG -- [req_id cpi-958342]: Running method 'FindByInventoryPath'...
D, [2018-12-21T06:19:58.838236 #11853] DEBUG -- [req_id cpi-958342]: Running method 'CreateContainerView'...
D, [2018-12-21T06:19:58.935989 #11853] DEBUG -- [req_id cpi-958342]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-21T06:19:59.108488 #11853] DEBUG -- [req_id cpi-958342]: Running method 'FindByInventoryPath'...
I, [2018-12-21T06:20:00.500762 #11853]  INFO -- [req_id cpi-958342]: Cloning vm: (VSphereCloud::Resources::VM (cid="sc-c94935ea-2af4-4416-8947-665d115e7474")) to vm-0ccac867-38e3-48bb-afc4-f91fe982b1d0
D, [2018-12-21T06:20:00.501017 #11853] DEBUG -- [req_id cpi-958342]: Running method 'FindByInventoryPath'...
D, [2018-12-21T06:20:00.525739 #11853] DEBUG -- [req_id cpi-958342]: Found requested resource pool: <[Vim.ResourcePool] resgroup-1499>
D, [2018-12-21T06:20:00.526740 #11853] DEBUG -- [req_id cpi-958342]: Running method 'CloneVM_Task'...
D, [2018-12-21T06:20:00.554495 #11853] DEBUG -- [req_id cpi-958342]: Starting task 'VirtualMachine.clone'...
D, [2018-12-21T06:20:09.994366 #11853] DEBUG -- [req_id cpi-958342]: Finished task 'VirtualMachine.clone' after 9.43965342 seconds
I, [2018-12-21T06:20:10.044862 #11853]  INFO -- [req_id cpi-958342]: Updating current agent env from vm 'vm-0ccac867-38e3-48bb-afc4-f91fe982b1d0' in datacenter 'DK-DC'
I, [2018-12-21T06:20:10.093010 #11853]  INFO -- [req_id cpi-958342]: Cleaning current agent env from vm 'vm-0ccac867-38e3-48bb-afc4-f91fe982b1d0'
I, [2018-12-21T06:20:10.132123 #11853]  INFO -- [req_id cpi-958342]: Uploading file to https://<VC_IP>/folder/vm-0ccac867-38e3-48bb-afc4-f91fe982b1d0/env.json?dcPath=DK-DC&dsName=PAS2_vsanDatastore...
I, [2018-12-21T06:20:11.135166 #11853]  INFO -- [req_id cpi-958342]: Successfully uploaded file.
I, [2018-12-21T06:20:11.140458 #11853]  INFO -- [req_id cpi-958342]: Uploading file to https://<VC_IP>folder/vm-0ccac867-38e3-48bb-afc4-f91fe982b1d0/env.iso?dcPath=DK-DC&dsName=PAS2_vsanDatastore...
I, [2018-12-21T06:20:11.779754 #11853]  INFO -- [req_id cpi-958342]: Successfully uploaded file.
D, [2018-12-21T06:20:11.863362 #11853] DEBUG -- [req_id cpi-958342]: Running method 'ReconfigVM_Task'...
D, [2018-12-21T06:20:11.888629 #11853] DEBUG -- [req_id cpi-958342]: Starting task 'VirtualMachine.reconfigure'...
D, [2018-12-21T06:20:12.917259 #11853] DEBUG -- [req_id cpi-958342]: Finished task 'VirtualMachine.reconfigure' after 1.028414361 seconds
I, [2018-12-21T06:20:12.941250 #11853]  INFO -- [req_id cpi-958342]: Powering on VM: (VSphereCloud::Resources::VM (cid="vm-0ccac867-38e3-48bb-afc4-f91fe982b1d0"))
D, [2018-12-21T06:20:12.986543 #11853] DEBUG -- [req_id cpi-958342]: Running method 'PowerOnMultiVM_Task'...
D, [2018-12-21T06:20:13.010093 #11853] DEBUG -- [req_id cpi-958342]: Starting task 'Datacenter.powerOnVm'...
D, [2018-12-21T06:20:13.022423 #11853] DEBUG -- [req_id cpi-958342]: Finished task 'Datacenter.powerOnVm' after 0.012123718 seconds
D, [2018-12-21T06:20:13.033665 #11853] DEBUG -- [req_id cpi-958342]: Starting task 'Drm.ExecuteVmPowerOnLRO'...
D, [2018-12-21T06:20:15.075146 #11853] DEBUG -- [req_id cpi-958342]: Finished task 'Drm.ExecuteVmPowerOnLRO' after 2.041265506 seconds
I, [2018-12-21T06:20:15.075520 #11853]  INFO -- [req_id cpi-958342]: Finished create_vm in 17.11 seconds
D, [2018-12-21T06:20:15.076290 #11853] DEBUG -- [req_id cpi-958342]: Running method 'Logout'...
/var/vcap/data/packages/vsphere_cpi/6a846bc126536d490e43d8762cff951456af41ca/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2018-12-21T06:20:22.598756 #12509]  INFO -- [req_id cpi-720359]: Starting info...
D, [2018-12-21T06:20:22.601087 #12509] DEBUG -- [req_id cpi-720359]: Running method 'RetrieveServiceContent'...
D, [2018-12-21T06:20:22.654600 #12509] DEBUG -- [req_id cpi-720359]: Running method 'Login'...
I, [2018-12-21T06:20:22.693536 #12509]  INFO -- [req_id cpi-720359]: Finished info in 0.09 seconds
D, [2018-12-21T06:20:22.694099 #12509] DEBUG -- [req_id cpi-720359]: Running method 'Logout'...
/var/vcap/data/packages/vsphere_cpi/6a846bc126536d490e43d8762cff951456af41ca/lib/ruby_vim_sdk/vmomi_support.rb:56: warning: constant ::Fixnum is deprecated
I, [2018-12-21T06:20:29.815920 #12528]  INFO -- [req_id cpi-149172]: Starting set_vm_metadata...
D, [2018-12-21T06:20:29.818270 #12528] DEBUG -- [req_id cpi-149172]: Running method 'RetrieveServiceContent'...
D, [2018-12-21T06:20:29.883306 #12528] DEBUG -- [req_id cpi-149172]: Running method 'Login'...
D, [2018-12-21T06:20:29.921431 #12528] DEBUG -- [req_id cpi-149172]: Running method 'FindByInventoryPath'...
D, [2018-12-21T06:20:29.928509 #12528] DEBUG -- [req_id cpi-149172]: Running method 'CreateContainerView'...
D, [2018-12-21T06:20:30.030798 #12528] DEBUG -- [req_id cpi-149172]: Running method 'ContinueRetrievePropertiesEx'...
D, [2018-12-21T06:20:30.087986 #12528] DEBUG -- [req_id cpi-149172]: Running method 'AddCustomFieldDef'...
W, [2018-12-21T06:20:30.095800 #12528]  WARN -- [req_id cpi-149172]: Error running method 'AddCustomFieldDef'. Failed with message 'The name 'director' already exists.'.
W, [2018-12-21T06:20:30.095981 #12528]  WARN -- [req_id cpi-149172]: Custom field definition already exists: The name 'director' already exists.
D, [2018-12-21T06:20:30.118993 #12528] DEBUG -- [req_id cpi-149172]: Running method 'SetField'...
D, [2018-12-21T06:20:30.126059 #12528] DEBUG -- [req_id cpi-149172]: Running method 'AddCustomFieldDef'...
W, [2018-12-21T06:20:30.134740 #12528]  WARN -- [req_id cpi-149172]: Error running method 'AddCustomFieldDef'. Failed with message 'The name 'deployment' already exists.'.
W, [2018-12-21T06:20:30.135097 #12528]  WARN -- [req_id cpi-149172]: Custom field definition already exists: The name 'deployment' already exists.
D, [2018-12-21T06:20:30.158197 #12528] DEBUG -- [req_id cpi-149172]: Running method 'SetField'...
D, [2018-12-21T06:20:30.165157 #12528] DEBUG -- [req_id cpi-149172]: Running method 'AddCustomFieldDef'...
W, [2018-12-21T06:20:30.173450 #12528]  WARN -- [req_id cpi-149172]: Error running method 'AddCustomFieldDef'. Failed with message 'The name 'id' already exists.'.
W, [2018-12-21T06:20:30.173685 #12528]  WARN -- [req_id cpi-149172]: Custom field definition already exists: The name 'id' already exists.
D, [2018-12-21T06:20:30.196171 #12528] DEBUG -- [req_id cpi-149172]: Running method 'SetField'...
D, [2018-12-21T06:20:30.204214 #12528] DEBUG -- [req_id cpi-149172]: Running method 'AddCustomFieldDef'...
W, [2018-12-21T06:20:30.211921 #12528]  WARN -- [req_id cpi-149172]: Error running method 'AddCustomFieldDef'. Failed with message 'The name 'job' already exists.'.
W, [2018-12-21T06:20:30.212155 #12528]  WARN -- [req_id cpi-149172]: Custom field definition already exists: The name 'job' already exists.
D, [2018-12-21T06:20:30.238982 #12528] DEBUG -- [req_id cpi-149172]: Running method 'SetField'...
D, [2018-12-21T06:20:30.246073 #12528] DEBUG -- [req_id cpi-149172]: Running method 'AddCustomFieldDef'...
W, [2018-12-21T06:20:30.254061 #12528]  WARN -- [req_id cpi-149172]: Error running method 'AddCustomFieldDef'. Failed with message 'The name 'instance_group' already exists.'.
W, [2018-12-21T06:20:30.254279 #12528]  WARN -- [req_id cpi-149172]: Custom field definition already exists: The name 'instance_group' already exists.
D, [2018-12-21T06:20:30.278715 #12528] DEBUG -- [req_id cpi-149172]: Running method 'SetField'...
D, [2018-12-21T06:20:30.286412 #12528] DEBUG -- [req_id cpi-149172]: Running method 'AddCustomFieldDef'...
W, [2018-12-21T06:20:30.293196 #12528]  WARN -- [req_id cpi-149172]: Error running method 'AddCustomFieldDef'. Failed with message 'The name 'index' already exists.'.
W, [2018-12-21T06:20:30.293390 #12528]  WARN -- [req_id cpi-149172]: Custom field definition already exists: The name 'index' already exists.
D, [2018-12-21T06:20:30.315534 #12528] DEBUG -- [req_id cpi-149172]: Running method 'SetField'...
D, [2018-12-21T06:20:30.322501 #12528] DEBUG -- [req_id cpi-149172]: Running method 'AddCustomFieldDef'...
W, [2018-12-21T06:20:30.329818 #12528]  WARN -- [req_id cpi-149172]: Error running method 'AddCustomFieldDef'. Failed with message 'The name 'name' already exists.'.
W, [2018-12-21T06:20:30.329996 #12528]  WARN -- [req_id cpi-149172]: Custom field definition already exists: The name 'name' already exists.
D, [2018-12-21T06:20:30.353134 #12528] DEBUG -- [req_id cpi-149172]: Running method 'SetField'...
D, [2018-12-21T06:20:30.360649 #12528] DEBUG -- [req_id cpi-149172]: Running method 'AddCustomFieldDef'...
W, [2018-12-21T06:20:30.368140 #12528]  WARN -- [req_id cpi-149172]: Error running method 'AddCustomFieldDef'. Failed with message 'The name 'created_at' already exists.'.
W, [2018-12-21T06:20:30.368338 #12528]  WARN -- [req_id cpi-149172]: Custom field definition already exists: The name 'created_at' already exists.
D, [2018-12-21T06:20:30.390809 #12528] DEBUG -- [req_id cpi-149172]: Running method 'SetField'...
I, [2018-12-21T06:20:30.457810 #12528]  INFO -- [req_id cpi-149172]: NSX-T networks found for vm 'vm-0ccac867-38e3-48bb-afc4-f91fe982b1d0': ["nsx.LogicalSwitch: f67c1a71-7c7c-4a08-85f9-1ce400e71edb"]
I, [2018-12-21T06:20:30.458141 #12528]  INFO -- [req_id cpi-149172]: Searching for LogicalPorts for vm 'vm-0ccac867-38e3-48bb-afc4-f91fe982b1d0'
I, [2018-12-21T06:20:30.504813 #12528]  INFO -- [req_id cpi-149172]: Searching VIFs with 'owner_vm_id: 500d6a8a-8e2e-b146-d249-2b5d88c0bed3'
I, [2018-12-21T06:20:30.528093 #12528]  INFO -- [req_id cpi-149172]: Searching LogicalPorts with 'attachment_id: cb2576f4-4ae9-40d3-b3ce-6c523f222f27'
I, [2018-12-21T06:20:30.550410 #12528]  INFO -- [req_id cpi-149172]: LogicalPorts found for vm 'vm-0ccac867-38e3-48bb-afc4-f91fe982b1d0': ["12a964a5-e491-46ca-b330-8ff0f4c4ad74"]'
I, [2018-12-21T06:20:30.609198 #12528]  INFO -- [req_id cpi-149172]: Finished set_vm_metadata in 0.79 seconds
D, [2018-12-21T06:20:30.610437 #12528] DEBUG -- [req_id cpi-149172]: Running method 'Logout'...

Task 49066 error
```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Release Version & Related Info (please complete the following information):**
 - CPI Version :  `vsphere_cpi 267.7.0`
 - BOSH Director Version: `version 5.1.2-14b04789-2018-08-17T15:15:17Z`
 - Stemcell Name & Version: `ubuntu-xenial 97.34`
 - vCenter Version: `vSphere Client version 6.7.0`
 - NSX-T Version:  `VMware NSX-T 2.3.1`

**Comment by EleanorRigby** [comment] 2018-12-21 18:12
@Nilesh7756 
I and @xetamus discussed this on slack. I will share our discussion here 


 This IP is also allocated by BOSH from the network range specified in cloud config like this below
```networks:
- name: default
  subnets:
  - azs:
    - z1
    - z2
    cloud_properties:
      name: 'VM Network'
    dns:
    - 192.168.111.1
    gateway: 192.168.111.129
    range: 192.168.111.1/24
    reserved: [192.168.111.0-192.168.111.155]
  type: manual```
Let's say BOSH uses `192.168.111.166` to create gorouter VM. You add this IP in LB pool manually , external to CPI. Now as per your request , during one of the re create operation of whole foundation , this VM gets deleted but membership stays. Now BOSH re creates whole deployment and is re creating a Diego Cell or MySQL vm and BOSH now knows this IP `192.168.111.166` is free and allocates it to Diego/MySQL VM.  As an effect this VM gets added to server pool because we did not delete the association.  I think this workflow is legal in BOSH world and can cause much bigger problems like not being able to reach database vm.

**Comment by EleanorRigby** [comment] 2018-12-21 18:14
Also @Nilesh7756 , can you provide right CPI version above. The version provided by you above is for `Director` not for the `CPI`.

**Comment by Nilesh7756** [comment] 2018-12-21 18:45
Yes, sure!! Correct CPI version: `bosh-vsphere-cpi 50`

What you explained over here make sense to me, regarding legal BOSH workflow. 
But the deletion of NSX-T Pool members from Server Pool by CPI, here creating the major issue in ENV.

**Comment by EleanorRigby** [comment] 2018-12-21 20:09
@Nilesh7756 : Thanks for the logs and input. We  will think about some solution when we work on this story. *However, seems unlikely CPI can do anything about it.* 

I would suggest using cloud properties to attach the VM's IP to server pool rather than doing it manually. That way when you re create it will re add.

**Comment by EleanorRigby** [comment] 2019-04-03 20:33
Closing the issue for lack of sufficient knowledge and evidence to prove that the observed behaviour is a bug.

Feel free to open this with more information.

**Closed by EleanorRigby** 2019-04-03 20:33 UTC
Labels: discuss
